#---------------------------------------------------------------------------
MAKEFILE_PATH := $(abspath $(lastword ${MAKEFILE_LIST}))
MAKEFILE_DIR := $(dir ${MAKEFILE_PATH})
#---------------------------------------------------------------------------
BREW := $(shell command -v brew 2> /dev/null)
ZSH := $(shell command -v zsh 2> /dev/null)
NVIM := $(shell command -v nvim 2> /dev/null)
TMUX := $(shell command -v tmux 2> /dev/null)
#---------------------------------------------------------------------------
print-environment:
	@echo "λ  MAKEFILE_PATH: ${MAKEFILE_PATH}"
	@echo "λ  MAKEFILE_DIR: ${MAKEFILE_DIR}"
#---------------------------------------------------------------------------
create-npm-root:
	@mkdir -p ~/.npm_global
#---------------------------------------------------------------------------
install-brew:
ifndef BREW
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	@echo "λ  Found Homebrew: ${BREW}"
endif
#---------------------------------------------------------------------------
install-nvim: install-brew
ifndef NVIM
	brew install python3
	brew install neovim/neovim/neovim
	pip3 install neovim
else
	@echo "λ  Found Neovim: ${NVIM}"
endif
	@echo "λ  Required: https://github.com/ryanoasis/nerd-fonts"
	@echo "λ  Recommended: White terminal theme with BG RGB(238,238,238)"
#---------------------------------------------------------------------------
install-tmux: install-brew
ifndef TMUX
	brew install tmux
	brew install reattach-to-user-namespace
else
	@echo "λ  Found Tmux: ${TMUX}"
endif
#---------------------------------------------------------------------------
install-zsh: install-brew
ifndef ZSH
	brew install zsh
else
	@echo "λ  Found Zsh: ${ZSH}"
endif
#---------------------------------------------------------------------------
install-symlinks:
	@echo "λ  Linking Neovim configuration"
	@mkdir -p ~/.config/
	@sh -c "[ ! -L ${MAKEFILE_DIR}nvim ] || rm ${MAKEFILE_DIR}nvim;"
	@ln -sf ${MAKEFILE_DIR}nvim ~/.config/
	@echo "λ  Linking Zsh configuration"
	@ln -sf ${MAKEFILE_DIR}zsh/zshrc.symlink ~/.zshrc
	@echo "λ  Linking Tmux configuration"
	@ln -sf ${MAKEFILE_DIR}tmux/tmux.conf.symlink ~/.tmux.conf
	@echo "λ  Setting Zsh shell"
	@grep -q -F `which zsh` /etc/shells || echo `which zsh` | sudo tee -a /etc/shells > /dev/null
	@chsh -s `which zsh`
#---------------------------------------------------------------------------
install: print-environment install-zsh install-nvim install-tmux install-symlinks create-npm-root
#---------------------------------------------------------------------------
